CREATE DATABASE IF NOT EXISTS Smart_payment_System;
USE Smart_payment_System;

CREATE TABLE IF NOT EXISTS sps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    UPIID VARCHAR(255) NOT NULL,
    PIN VARCHAR(255) NOT NULL
);

INSERT INTO sps (UPIID, PIN) VALUES ('devendra', '1234');
INSERT INTO sps (UPIID, PIN) VALUES (?, ?);


SELECT * FROM sps;
